#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

#!/bin/sh

#Get the current branch
branch=$(git rev-parse --symbolic --abbrev-ref HEAD)

#Check if the current branch is one of the main branches
echo Main branch must Pass all Jest Tests before push
if [[ "$branch" =~ ^Versions\/.* ]];
then
    if ! npm test;
    then
        exit 1
    fi
fi